module.exports = [ { wiringPi: 0,
    GPIO: 17,
    Phys: 11,
    Name: 'GPIO 0',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 1,
    GPIO: 18,
    Phys: 12,
    Name: 'GPIO 1',
    Mode: 'OUT',
    Value: 'Low' },
  { wiringPi: 2,
    GPIO: 27,
    Phys: 13,
    Name: 'GPIO 2',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 3,
    GPIO: 22,
    Phys: 15,
    Name: 'GPIO 3',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 4,
    GPIO: 23,
    Phys: 16,
    Name: 'GPIO 4',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 5,
    GPIO: 24,
    Phys: 18,
    Name: 'GPIO 5',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 6,
    GPIO: 25,
    Phys: 22,
    Name: 'GPIO 6',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 7,
    GPIO: 4,
    Phys: 7,
    Name: 'GPIO 7',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 8,
    GPIO: 2,
    Phys: 3,
    Name: 'SDA',
    Mode: 'IN',
    Value: 'High' },
  { wiringPi: 9,
    GPIO: 3,
    Phys: 5,
    Name: 'SCL',
    Mode: 'IN',
    Value: 'High' },
  { wiringPi: 10,
    GPIO: 8,
    Phys: 24,
    Name: 'CE0',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 11,
    GPIO: 7,
    Phys: 26,
    Name: 'CE1',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 12,
    GPIO: 10,
    Phys: 19,
    Name: 'MOSI',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 13,
    GPIO: 9,
    Phys: 21,
    Name: 'MISO',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 14,
    GPIO: 11,
    Phys: 23,
    Name: 'SCLK',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 15,
    GPIO: 14,
    Phys: 8,
    Name: 'TxD',
    Mode: 'ALT0',
    Value: 'High' },
  { wiringPi: 16,
    GPIO: 15,
    Phys: 10,
    Name: 'RxD',
    Mode: 'ALT0',
    Value: 'High' },
  { wiringPi: 17,
    GPIO: 28,
    Phys: 3,
    Name: 'GPIO 8',
    Mode: 'IN',
    Value: 'Low' },
  { wiringPi: 18,
    GPIO: 29,
    Phys: 4,
    Name: 'GPIO 9',
    Mode: 'OUT',
    Value: 'Low' },
  { wiringPi: 19,
    GPIO: 30,
    Phys: 5,
    Name: 'GPIO10',
    Mode: 'IN',
    Value: 'Low' } ];